# permissions for end users to view kudofluxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kudoflux-viewer-role
rules:
- apiGroups:
  - flux.kudo.dev
  resources:
  - kudofluxes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - flux.kudo.dev
  resources:
  - kudofluxes/status
  verbs:
  - get
