# permissions for end users to edit kudofluxes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kudoflux-editor-role
rules:
- apiGroups:
  - flux.kudo.dev
  resources:
  - kudofluxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - flux.kudo.dev
  resources:
  - kudofluxes/status
  verbs:
  - get
